//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XComosMobile.Properties {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XComosMobile.Properties.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Info.
        /// </summary>
        internal static string basic_info {
            get {
                return ResourceManager.GetString("basic_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attributes saved in cache!.
        /// </summary>
        internal static string cached_attributes {
            get {
                return ResourceManager.GetString("cached_attributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incident created in cache!.
        /// </summary>
        internal static string cached_incident {
            get {
                return ResourceManager.GetString("cached_incident", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose theme.
        /// </summary>
        internal static string choose_theme {
            get {
                return ResourceManager.GetString("choose_theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting ....
        /// </summary>
        internal static string connecting {
            get {
                return ResourceManager.GetString("connecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create incident.
        /// </summary>
        internal static string create_incident {
            get {
                return ResourceManager.GetString("create_incident", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating Incidents....
        /// </summary>
        internal static string creating_incidents {
            get {
                return ResourceManager.GetString("creating_incidents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating Item....
        /// </summary>
        internal static string creating_item {
            get {
                return ResourceManager.GetString("creating_item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Base.
        /// </summary>
        internal static string data_base {
            get {
                return ResourceManager.GetString("data_base", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string delete {
            get {
                return ResourceManager.GetString("delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete?.
        /// </summary>
        internal static string delete_question {
            get {
                return ResourceManager.GetString("delete_question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string description {
            get {
                return ResourceManager.GetString("description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document not found!.
        /// </summary>
        internal static string document_not_found {
            get {
                return ResourceManager.GetString("document_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documents.
        /// </summary>
        internal static string documents {
            get {
                return ResourceManager.GetString("documents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domain Name.
        /// </summary>
        internal static string domain_name {
            get {
                return ResourceManager.GetString("domain_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done!.
        /// </summary>
        internal static string done {
            get {
                return ResourceManager.GetString("done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download finished!.
        /// </summary>
        internal static string download_done {
            get {
                return ResourceManager.GetString("download_done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download failed!.
        /// </summary>
        internal static string download_failed {
            get {
                return ResourceManager.GetString("download_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished downloading tasks!.
        /// </summary>
        internal static string download_tasks_done {
            get {
                return ResourceManager.GetString("download_tasks_done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading documents....
        /// </summary>
        internal static string downloading_documents {
            get {
                return ResourceManager.GetString("downloading_documents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading Workpackages....
        /// </summary>
        internal static string downloading_packages {
            get {
                return ResourceManager.GetString("downloading_packages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading Tasks....
        /// </summary>
        internal static string downloading_tasks {
            get {
                return ResourceManager.GetString("downloading_tasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can only download tasks online!.
        /// </summary>
        internal static string downloading_tasks_only_online {
            get {
                return ResourceManager.GetString("downloading_tasks_only_online", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error!.
        /// </summary>
        internal static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event container.
        /// </summary>
        internal static string event_container {
            get {
                return ResourceManager.GetString("event_container", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Event Container query was not found!.
        /// </summary>
        internal static string event_container_not_found {
            get {
                return ResourceManager.GetString("event_container_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetching Query....
        /// </summary>
        internal static string fetch_query {
            get {
                return ResourceManager.GetString("fetch_query", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found Material.
        /// </summary>
        internal static string found_material {
            get {
                return ResourceManager.GetString("found_material", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found Materials.
        /// </summary>
        internal static string found_materials {
            get {
                return ResourceManager.GetString("found_materials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to go offline?.
        /// </summary>
        internal static string go_offline {
            get {
                return ResourceManager.GetString("go_offline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string home {
            get {
                return ResourceManager.GetString("home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incident created!.
        /// </summary>
        internal static string incident_created {
            get {
                return ResourceManager.GetString("incident_created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incidents.
        /// </summary>
        internal static string Incidents {
            get {
                return ResourceManager.GetString("Incidents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inform tag?.
        /// </summary>
        internal static string inform_tag_reference {
            get {
                return ResourceManager.GetString("inform_tag_reference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inspection.
        /// </summary>
        internal static string Inspection {
            get {
                return ResourceManager.GetString("Inspection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inspections.
        /// </summary>
        internal static string Inspections {
            get {
                return ResourceManager.GetString("Inspections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item saved in cache!.
        /// </summary>
        internal static string item_cached {
            get {
                return ResourceManager.GetString("item_cached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item created!.
        /// </summary>
        internal static string item_created {
            get {
                return ResourceManager.GetString("item_created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string language {
            get {
                return ResourceManager.GetString("language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link not found!.
        /// </summary>
        internal static string link_not_found {
            get {
                return ResourceManager.GetString("link_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        internal static string loading {
            get {
                return ResourceManager.GetString("loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Events....
        /// </summary>
        internal static string loading_events {
            get {
                return ResourceManager.GetString("loading_events", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Incident Types....
        /// </summary>
        internal static string loading_incident_types {
            get {
                return ResourceManager.GetString("loading_incident_types", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Tasks....
        /// </summary>
        internal static string loading_tasks {
            get {
                return ResourceManager.GetString("loading_tasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Workpackages....
        /// </summary>
        internal static string loading_wp {
            get {
                return ResourceManager.GetString("loading_wp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot login!.
        /// </summary>
        internal static string login_error {
            get {
                return ResourceManager.GetString("login_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log-off.
        /// </summary>
        internal static string logoff {
            get {
                return ResourceManager.GetString("logoff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LogOut.
        /// </summary>
        internal static string logout {
            get {
                return ResourceManager.GetString("logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve Logged Out successfully.
        /// </summary>
        internal static string logout_reference {
            get {
                return ResourceManager.GetString("logout_reference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintenance.
        /// </summary>
        internal static string Maintenance {
            get {
                return ResourceManager.GetString("Maintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media.
        /// </summary>
        internal static string media {
            get {
                return ResourceManager.GetString("media", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The mobile tab was not found!.
        /// </summary>
        internal static string mobile_tab_not_found {
            get {
                return ResourceManager.GetString("mobile_tab_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Incident Types query was not found!.
        /// </summary>
        internal static string my_incidents_not_found {
            get {
                return ResourceManager.GetString("my_incidents_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My tasks.
        /// </summary>
        internal static string my_tasks {
            get {
                return ResourceManager.GetString("my_tasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The My tasks query was not found!.
        /// </summary>
        internal static string my_tasks_not_found {
            get {
                return ResourceManager.GetString("my_tasks_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My workpackages.
        /// </summary>
        internal static string my_workpackages {
            get {
                return ResourceManager.GetString("my_workpackages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The My workpackages query was not found!.
        /// </summary>
        internal static string my_wp_not_found {
            get {
                return ResourceManager.GetString("my_wp_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New incident.
        /// </summary>
        internal static string new_incident {
            get {
                return ResourceManager.GetString("new_incident", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new.
        /// </summary>
        internal static string new_item {
            get {
                return ResourceManager.GetString("new_item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string no {
            get {
                return ResourceManager.GetString("no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unauthorized access!.
        /// </summary>
        internal static string no_access {
            get {
                return ResourceManager.GetString("no_access", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This object doesn&apos;t have attributes!.
        /// </summary>
        internal static string no_attributes {
            get {
                return ResourceManager.GetString("no_attributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No incident types were found!.
        /// </summary>
        internal static string no_incidents_types_found {
            get {
                return ResourceManager.GetString("no_incidents_types_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No network!.
        /// </summary>
        internal static string no_network {
            get {
                return ResourceManager.GetString("no_network", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No tasks were found!.
        /// </summary>
        internal static string no_tasks_found {
            get {
                return ResourceManager.GetString("no_tasks_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No unassigned events were found!.
        /// </summary>
        internal static string no_unassigned_events_found {
            get {
                return ResourceManager.GetString("no_unassigned_events_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No workpackages were found!.
        /// </summary>
        internal static string no_wp_found {
            get {
                return ResourceManager.GetString("no_wp_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t upload offline.
        /// </summary>
        internal static string offline_upload {
            get {
                return ResourceManager.GetString("offline_upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open with.
        /// </summary>
        internal static string open_with {
            get {
                return ResourceManager.GetString("open_with", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working Overlay.
        /// </summary>
        internal static string overlay {
            get {
                return ResourceManager.GetString("overlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string PageLogin {
            get {
                return ResourceManager.GetString("PageLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a Project.
        /// </summary>
        internal static string PageProjects {
            get {
                return ResourceManager.GetString("PageProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        internal static string project {
            get {
                return ResourceManager.GetString("project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Tree.
        /// </summary>
        internal static string project_tree {
            get {
                return ResourceManager.GetString("project_tree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects.
        /// </summary>
        internal static string projects {
            get {
                return ResourceManager.GetString("projects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QR-Code error.
        /// </summary>
        internal static string QR_error {
            get {
                return ResourceManager.GetString("QR_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while reading QR code.
        /// </summary>
        internal static string QR_error_message {
            get {
                return ResourceManager.GetString("QR_error_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query @ not found!.
        /// </summary>
        internal static string query_not_found {
            get {
                return ResourceManager.GetString("query_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reloging....
        /// </summary>
        internal static string reloging {
            get {
                return ResourceManager.GetString("reloging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember Password.
        /// </summary>
        internal static string Remember_password {
            get {
                return ResourceManager.GetString("Remember_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @ results were found!.
        /// </summary>
        internal static string results_found {
            get {
                return ResourceManager.GetString("results_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save failed!.
        /// </summary>
        internal static string save_failed {
            get {
                return ResourceManager.GetString("save_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It&apos;s not possible to save the document!.
        /// </summary>
        internal static string save_not_possible {
            get {
                return ResourceManager.GetString("save_not_possible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save changes?.
        /// </summary>
        internal static string save_question {
            get {
                return ResourceManager.GetString("save_question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving....
        /// </summary>
        internal static string saving {
            get {
                return ResourceManager.GetString("saving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving Tasks....
        /// </summary>
        internal static string saving_tasks {
            get {
                return ResourceManager.GetString("saving_tasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error trying to search:.
        /// </summary>
        internal static string search_error {
            get {
                return ResourceManager.GetString("search_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Material.
        /// </summary>
        internal static string search_material {
            get {
                return ResourceManager.GetString("search_material", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching....
        /// </summary>
        internal static string searching {
            get {
                return ResourceManager.GetString("searching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        internal static string select {
            get {
                return ResourceManager.GetString("select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comos Web Address.
        /// </summary>
        internal static string server_address {
            get {
                return ResourceManager.GetString("server_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Webservice Address.
        /// </summary>
        internal static string server_address_br {
            get {
                return ResourceManager.GetString("server_address_br", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server error!.
        /// </summary>
        internal static string server_error {
            get {
                return ResourceManager.GetString("server_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifications.
        /// </summary>
        internal static string specifications {
            get {
                return ResourceManager.GetString("specifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task not found!.
        /// </summary>
        internal static string task_not_found {
            get {
                return ResourceManager.GetString("task_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tasks.
        /// </summary>
        internal static string Tasks {
            get {
                return ResourceManager.GetString("Tasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        internal static string theme {
            get {
                return ResourceManager.GetString("theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login request timed out!.
        /// </summary>
        internal static string timeout {
            get {
                return ResourceManager.GetString("timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unassigned Incident not found!.
        /// </summary>
        internal static string unassigned_incident_not_found {
            get {
                return ResourceManager.GetString("unassigned_incident_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        internal static string upload {
            get {
                return ResourceManager.GetString("upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload failed!.
        /// </summary>
        internal static string upload_failed {
            get {
                return ResourceManager.GetString("upload_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload done!.
        /// </summary>
        internal static string upload_sucess {
            get {
                return ResourceManager.GetString("upload_sucess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can only upload tasks online!.
        /// </summary>
        internal static string uploading_tasks_only_online {
            get {
                return ResourceManager.GetString("uploading_tasks_only_online", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        internal static string user_name {
            get {
                return ResourceManager.GetString("user_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workpackages.
        /// </summary>
        internal static string worckpackages {
            get {
                return ResourceManager.GetString("worckpackages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string yes {
            get {
                return ResourceManager.GetString("yes", resourceCulture);
            }
        }
    }
}
